# Generated by Django 4.1.7 on 2023-03-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0002_video_likes_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
